# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 21.1.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.2-fpm-0
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  appdata:
  dbdata:
  sockdata:
