# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 23.0.0

version: "3"

services:
  proxy:
    #image: markoshust/magento-proxy:1.13-0
    image: willemwigman/magento-proxy:1.13-0
    ports:
      - "443:8443"
    depends_on:
      - varnish
    links:
      - varnish

  varnish:
    #image: markoshust/magento-varnish:latest
    image: willemwigman/magento-varnish:latest
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - app
    links:
      - app

  app:
    #image: markoshust/magento-nginx:1.13-8
    image: willemwigman/magento-nginx:1.13-8
    ports:
      - "8000:8000"
    depends_on:
      - db
      - phpfpm
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock

  phpfpm:
    #image: markoshust/magento-php:7.2-fpm-0
    #image: markoshust/magento-php:7.1-fpm-1
    image: willemwigman/magento-php:7.2-fpm-0
    depends_on:
      - db
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.2-fpm-0
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
