# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 21.1.0

version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ~/.composer:/var/www/.composer:delegated
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      - ./src/composer.json:/var/www/html/composer.json:delegated
      - ./src/composer.lock:/var/www/html/composer.lock:delegated
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:delegated

  phpfpm:
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.2-fpm-0
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes
