# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 5.0.0

app:
  image: mageinferno/magento2-nginx:1.11-0
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
    - /var/www/html
#    - ~/.composer:/var/www/.composer
#    - ./html/app/code:/var/www/html/app/code
#    - ./html/app/design:/var/www/html/app/design

phpfpm:
  image: mageinferno/magento2-php:7.0-fpm-0
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://m2.localhost:8000/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_VERSION=2.1.2
    - M2SETUP_USE_SAMPLE_DATA=false
    - M2SETUP_USE_ARCHIVE=true
