# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 7.0.0

version: "3"

services:
  app:
    image: mageinferno/magento2-nginx:1.11-1
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
    ports:
      - 8000:80
    networks: &appnetworks
      - www

  phpfpm:
    image: mageinferno/magento2-php:7.0-fpm-1
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks

  db:
    image: percona:5.7
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 8001:3306
    networks: *appnetworks
    env_file: env/mysql.env

  setup:
    image: mageinferno/magento2-php:7.0-fpm-1
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: env/setup.env

volumes:
  dbdata:
  appdata:

networks:
  www:
