# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 6.0.0

app:
  image: mageinferno/magento2-nginx:1.11-1
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  ports:
    - 8000:80

appdata:
  image: tianon/true
  volumes:
    - /var/www/html

phpfpm:
  image: mageinferno/magento2-php:7.1-fpm-0
  links:
    - db
  volumes_from:
    - appdata

db:
  image: percona:5.7
  volumes_from:
    - dbdata
  ports:
    - 8001:3306
  env_file: env/mysql.env

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.1-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  env_file: env/setup.env
