# Mark Shust's Magento Docker Compose (https://github.com/markoshust/magento-docker)
# Version 11.1.3

version: "3"

services:
  app:
    build: images/nginx
    ports:
      - 80:80
    links:
      - db
      - phpfpm

  phpfpm:
    image: markoshust/magento-php:5.6-fpm
    links:
      - db

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
