# Mark Shust's Magento Docker Compose (https://github.com/markoshust/magento-docker)
# Version 11.1.3

version: "3"

services:
  app:
    volumes: &appvolumes
      - magento1_appdata:/var/www/html:nocopy
      - ~/.composer:/var/www/.composer

  phpfpm:
    volumes: *appvolumes

  db:
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  magento1_appdata:
    external: true
