# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 18.1.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-5
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/sock
      - appdata:/var/www/html/app
      - appdata:/var/www/html/bin
      - appdata:/var/www/html/dev
      - appdata:/var/www/html/generated
      - appdata:/var/www/html/lib
      - appdata:/var/www/html/phpserver
      - appdata:/var/www/html/pub
      - appdata:/var/www/html/setup
      - appdata:/var/www/html/update
      - appdata:/var/www/html/var
      - appdata:/var/www/html/vendor

  phpfpm:
    image: markoshust/magento-php:7.1-fpm-9
    links:
      - db
    volumes: *appvolumes

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.1-fpm-9
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  appdata:
  dbdata:
