# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 16.1.1

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-4
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
      - ./src/app:/var/www/html/app:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.1-fpm-7
    links:
      - db
    volumes: *appvolumes

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.1-fpm-7
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  appdata:
  dbdata:
  sockdata:
