## Mark Shust's Docker Configuration for Magento
## (https://github.com/markshust/docker-magento)
##
## Version 41.0.2

## To use SSH, see https://github.com/markshust/docker-magento#ssh
## Linux users, see https://github.com/markshust/docker-magento#linux

## If you changed the default Docker network, you may need to replace
## 172.17.0.1 in this file with the result of:
## docker network inspect bridge --format='{{(index .IPAM.Config 0).Gateway}}'

version: "3"

services:
  magento:
    container_name: 'magento'
    image: markoshust/magento-nginx:1.18
    restart: "unless-stopped"
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - /mnt/appdata:/var/www/html
      - /mnt/ssldata:/etc/nginx/certs
      - sockdata:/sock

  phpfpm:
    container_name: 'phpfpm'
    image: markoshust/magento-php:7.3-fpm
    restart: "unless-stopped"
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    container_name: 'sqlserver'
    image: mariadb:10.4
    restart: "unless-stopped"
    command: --max_allowed_packet=64M
    ports:
      - "127.0.0.1:3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    container_name: 'rediscache'
    image: redis:5.0-alpine
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:6379:6379"

  elasticsearch:
    container_name: 'elasticsearch'
    image: markoshust/magento-elasticsearch:7.9.3-1
    restart: "no"
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

volumes:
  dbdata:
  sockdata:
