# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 29.0.0

version: "3"

services:
  app:
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      - ./src/composer.json:/var/www/html/composer.json:delegated
      - ./src/composer.lock:/var/www/html/composer.lock:delegated
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:delegated
      - ./src/var/log:/var/www/html/var/log:delegated
      #- ./src/var/report:/var/www/html/var/report:delegated
      #- ./extensions/services-id/ServicesId:/var/www/html/app/code/Magento/ServicesId:consistent
      #- ./extensions/data-services/DataServices:/var/www/html/app/code/Magento/DataServices:consistent
      #- ./extensions/data-services/DataServicesMultishipping:/var/www/html/app/code/Magento/DataServicesMultishipping:consistent
      #- ./extensions/saas-export/app/code/Magento/DataExporter:/var/www/html/app/code/Magento/DataExporter:consistent
      #- ./extensions/saas-export/app/code/Magento/CatalogDataExporter:/var/www/html/app/code/Magento/CatalogDataExporter:consistent
      #- ./extensions/saas-export/app/code/Magento/CatalogInventoryDataExporter:/var/www/html/app/code/Magento/CatalogInventoryDataExporter:consistent
      #- ./extensions/saas-export/app/code/Magento/CatalogUrlRewriteDataExporter:/var/www/html/app/code/Magento/CatalogUrlRewriteDataExporter:consistent
      #- ./extensions/saas-export/app/code/Magento/ConfigurableProductDataExporter:/var/www/html/app/code/Magento/ConfigurableProductDataExporter:consistent
      #- ./extensions/saas-export/app/code/Magento/SaaSCatalog:/var/www/html/app/code/Magento/SaaSCatalog:consistent
      #- ./extensions/product-recommendations-admin/ProductRecommendationsAdmin:/var/www/html/app/code/Magento/ProductRecommendationsAdmin:consistent
      #- ./extensions/product-recommendations/ProductRecommendationsLayout:/var/www/html/app/code/Magento/ProductRecommendationsLayout:consistent

  phpfpm:
    env_file: env/magento.env
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db

  # Disabling cron by default as it uses higher CPU, enable if needed
  cron:
    volumes: *appvolumes
